[theme]
theme = "dracula"

[icons]
#icons = "awesome5"
icons = "material-nf"
#icons_format = " <span font_family='FiraCode Nerd Font Mono'>{icon}</span> "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
#unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $available $path"

[[block]]
block = "memory"
format = "$mem_used/$mem_total"

[[block]]
block = "cpu"
interval = 1
format = "$barchart $utilization $frequency"


[[block]]
block = "battery"
interval = 10
#hide_missing = true


[[block]]
block = "sound"

[[block]]
block = "net"
#on_click = "alacritty -e nmtui"
missing_format = "-=No Wireless=-"
#interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
#interface_name_include = []
format = "$icon$ssid"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %R', l:en_US)"
