
[colors]
draw_bold_text_with_bright_colors = true

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Mono"

[window]
dynamic_title = true
opacity = 0.95

[general]
import = ["~/.config/alacritty/orbit.toml"]
